@extends('layouts.admin')

@section('content')
<div class="container-fluid px-4">
  <h1 class="h3 my-3">REPORTS</h1>

  {{-- Breadcrumb --}}
  <nav aria-label="breadcrumb" class="mb-4">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="http://127.0.0.1:8000/admin/dashboard"><i class="bi bi-house"></i></a></li>
      <li class="breadcrumb-item active" aria-current="page">Reports</li>
    </ol>
  </nav>

  {{-- Top Buttons --}}
  <div class="d-flex justify-content-end align-items-center gap-2 mb-3">
    <button type="button" class="btn btn-outline-secondary">
      <i class="bi bi-arrow-clockwise"></i> Refresh
    </button>
    <button type="button" class="btn btn-dark">Filter by</button>
    <button type="button" class="btn btn-primary">Generate Report</button>

    <div class="btn-group">
      <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        Export
      </button>
      <ul class="dropdown-menu dropdown-menu-end">
        <li><a class="dropdown-item" href="#">Export as Excel</a></li>
        <li><a class="dropdown-item" href="#">Export as PDF</a></li>
      </ul>
    </div>
  </div>

  {{-- Search Bar --}}
  <div class="mb-3 d-flex justify-content-end">
      <input
        class="form-control me-2" 
        type="search" 
        name="search" 
        placeholder="Search reports" 
        aria-label="Search"
        value="{{ request('search') }}"
        style="max-width: 250px;"
      />
      <button class="btn btn-outline-secondary" type="submit" title="Clear Search">
        <i class="bi bi-search"></i>
      </button>
  </div>

  {{-- Reports Table with empty rows --}}
  <div class="table-responsive">
    <table class="table table-bordered text-center align-middle">
      <thead class="table-dark">
        <tr>
          <th>REPORT TYPE</th>
          <th>DESCRIPTION</th>
          <th>DATE GENERATED</th>
          <th>GENERATED BY</th>
          <th>STATUS</th>
          <th>ACTIONS</th>
        </tr>
      </thead>
      <tbody>
        {{-- Empty rows for future data --}}
        <tr>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <button class="btn btn-sm btn-outline-primary me-1" title="View"><i class="bi bi-eye"></i></button>
            <button class="btn btn-sm btn-outline-danger" title="Delete"><i class="bi bi-trash"></i></button>
          </td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <button class="btn btn-sm btn-outline-primary me-1" title="View"><i class="bi bi-eye"></i></button>
            <button class="btn btn-sm btn-outline-danger" title="Delete"><i class="bi bi-trash"></i></button>
          </td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <button class="btn btn-sm btn-outline-primary me-1" title="View"><i class="bi bi-eye"></i></button>
            <button class="btn btn-sm btn-outline-danger" title="Delete"><i class="bi bi-trash"></i></button>
          </td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <button class="btn btn-sm btn-outline-primary me-1" title="View"><i class="bi bi-eye"></i></button>
            <button class="btn btn-sm btn-outline-danger" title="Delete"><i class="bi bi-trash"></i></button>
          </td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
            <button class="btn btn-sm btn-outline-primary me-1" title="View"><i class="bi bi-eye"></i></button>
            <button class="btn btn-sm btn-outline-danger" title="Delete"><i class="bi bi-trash"></i></button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  {{-- Pagination and entries info --}}
  <div class="d-flex justify-content-between align-items-center mt-3">
    <div>Showing 0 to 0 of 0 entries</div>
    <nav aria-label="Page navigation">
      <ul class="pagination mb-0">
        <li class="page-item disabled">
          <span class="page-link">&laquo;</span>
        </li>
        <li class="page-item active"><span class="page-link">1</span></li>
      </ul>
    </nav>
  </div>
</div>
@endsection